### PR TITLE
Update test_cross_validate.R

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes an issue in revdep-checks for the forthcoming _parameters_ update. I fixed the affected test, which will fail in _parameters 0.18.2_ (to be submitted soon), because the structure of attributes has changed.

I suggest ignoring attributes for this test, as these are likely to change in future updates again.

Are you able to submit a fix of your package in time once _parameters 0.18.2_ is accepted on CRAN?

Thanks,
Daniel

### CODE REVIEW

**Comment by strengejacke** [comment]
Looks like failing checks are unrelated to my PR.

**Comment by LudvigOlsen** [comment]
Thanks Daniel,

As I recall, most of the checks are failing due to missing some latex to pdf tools. Haven't found time to fix that yet.

I agree that this test could be simplified. Would you mind updating your PR to only test the first list? That is, the one contain `Fold Column`, `estimate`, etc., but not the `class`, `row.names`, etc.

And yes, I should be able to get this on CRAN fairly soon!

**Comment by strengejacke** [comment]
The `ignore_attr = TRUE` argument should already take care of this (i.e. the attributes are ignored), I just added them for the sake of completeness. But I'm happy to update the PR, just testing against the values, not the attributes.

@IndrajeetPatil Do you have an idea regarding the setup of GHA?

**Comment by LudvigOlsen** [comment]
Thanks!

**Comment by IndrajeetPatil** [comment]
AFAICT, these are spurious build failures. @LudvigOlsen You'll just need to retrigger the failed builds and see if they fail again.

**Comment by LudvigOlsen** [comment]
@IndrajeetPatil I think it systematically fails with `Error in running tools::texi2pdf()` (though macOS-latest (devel) seems to instead have a problem with fetching R or something).

**Comment by IndrajeetPatil** [comment]
Exactly. The failures are unrelated to the changes in current PR.

**Comment by IndrajeetPatil** [comment]
Btw, you should upgrade to GHA v2 workflows:
https://github.com/r-lib/actions/tree/v2-branch/examples

**Comment by LudvigOlsen** [comment]
The PR is fine yes :) 

I will try updating the workflow and see what happens!

**Pull request merged**
